const { contextBridge, ipcRenderer } = require('electron');

async function call(channel, ...payload) {
  const result = await ipcRenderer.invoke(channel, ...payload);
  if (!result.ok) throw new Error(result.error);
  return result.data;
}

contextBridge.exposeInMainWorld('hap', {
  snapshot: () => call('gui:snapshot'),
  importProject: () => call('gui:importProject'),
  addProject: (input) => call('gui:addProject', input),
  removeProject: (id) => call('gui:removeProject', id),
  batchRemoveProjects: (ids) => call('gui:batchRemoveProjects', ids),
  upsertProvider: (input) => call('gui:upsertProvider', input),
  removeProvider: (id) => call('gui:removeProvider', id),
  batchRemoveProviders: (ids) => call('gui:batchRemoveProviders', ids),
  upsertModel: (input) => call('gui:upsertModel', input),
  removeModel: (alias) => call('gui:removeModel', alias),
  batchRemoveModels: (aliases) => call('gui:batchRemoveModels', aliases),
  upsertAgent: (input) => call('gui:upsertAgent', input),
  removeAgent: (id) => call('gui:removeAgent', id),
  openInVsCode: (path) => call('gui:openInVsCode', path),
  openInExplorer: (path) => call('gui:openInExplorer', path),
  openInTerminal: (path) => call('gui:openInTerminal', path),
  testProvider: (idOrConfig) => call('gui:testProvider', idOrConfig),
  fetchProviderModels: (providerId, options) => call('gui:fetchProviderModels', { providerId, options }),
  getProviderApiKey: (providerId) => call('gui:getProviderApiKey', providerId),
  getEnvVars: () => call('gui:getEnvVars'),
  saveEnvVar: (input) => call('gui:saveEnvVar', input),
  deleteEnvVar: (key) => call('gui:deleteEnvVar', key),
  batchSaveEnvVars: (entries) => call('gui:batchSaveEnvVars', entries),
  generateImage: (payload) => call('gui:generateImage', payload),
  listSkills: () => call('gui:listSkills'),
  installSkill: (repoUrl) => call('gui:installSkill', repoUrl),
  toggleSkill: (id, enabled) => call('gui:toggleSkill', { id, enabled }),
  uninstallSkill: (id) => call('gui:uninstallSkill', id),
  listPlugins: () => call('gui:listPlugins'),
  togglePlugin: (id, enabled) => call('gui:togglePlugin', { id, enabled }),
  upsertPlugin: (plugin) => call('gui:upsertPlugin', plugin),
  getPermissions: () => call('gui:getPermissions'),
  updatePermissions: (config) => call('gui:updatePermissions', config),
  getGitStatus: (projectPath) => call('gui:getGitStatus', projectPath),
  gitCommit: (projectPath, message) => call('gui:gitCommit', { projectPath, message }),
  gitPush: (projectPath) => call('gui:gitPush', projectPath),
  gitPull: (projectPath) => call('gui:gitPull', projectPath),
  gitDiff: (projectPath, file) => call('gui:gitDiff', { projectPath, file }),
  getVisualDiff: (projectPath, file) => call('gui:getVisualDiff', { projectPath, file }),
  revertFileDiff: (projectPath, file) => call('gui:revertFileDiff', { projectPath, file }),
  stageFileDiff: (projectPath, file) => call('gui:stageFileDiff', { projectPath, file }),
  stageHunk: (projectPath, file, patch) => call('gui:stageHunk', { projectPath, file, patch }),
  revertHunk: (projectPath, file, patch) => call('gui:revertHunk', { projectPath, file, patch }),
  listSchedules: () => call('gui:listSchedules'),
  upsertSchedule: (input) => call('gui:upsertSchedule', input),
  removeSchedule: (id) => call('gui:removeSchedule', id),
  toggleSchedule: (id, enabled) => call('gui:toggleSchedule', { id, enabled }),
  runScheduleNow: (id) => call('gui:runScheduleNow', id),
  getScheduleHistory: (scheduleId) => call('gui:getScheduleHistory', scheduleId),
  listMemories: (category) => call('gui:listMemories', category),
  addMemory: (input) => call('gui:addMemory', input),
  searchMemories: (query, limit) => call('gui:searchMemories', { query, limit }),
  removeMemory: (id) => call('gui:removeMemory', id),
  findDefinition: (symbol, workspace) => call('gui:findDefinition', { symbol, workspace }),
  findReferences: (symbol, workspace) => call('gui:findReferences', { symbol, workspace }),
  listSymbols: (file) => call('gui:listSymbols', file),
  getWebInfo: () => call('gui:getWebInfo'),
  getHostSysInfo: () => call('gui:getHostSysInfo'),
  scanDiskCleanable: (server) => call('gui:scanDiskCleanable', server),
  executeDiskCleanup: (payload) => call('gui:executeDiskCleanup', payload),
  getIpGeoInfo: (ip) => call('gui:getIpGeoInfo', ip),
  getTelegramConfig: () => call('gui:getTelegramConfig'),
  saveTelegramConfig: (config) => call('gui:saveTelegramConfig', config),
  testTelegramBot: (token) => call('gui:testTelegramBot', token),
  startTelegramService: () => call('gui:startTelegramService'),
  stopTelegramService: () => call('gui:stopTelegramService'),
  getWeChatConfig: () => call('gui:getWeChatConfig'),
  saveWeChatConfig: (config) => call('gui:saveWeChatConfig', config),
  startWeChatService: () => call('gui:startWeChatService'),
  stopWeChatService: () => call('gui:stopWeChatService'),
  refreshWeChatQr: () => call('gui:refreshWeChatQr'),
  confirmWeChatLogin: () => call('gui:confirmWeChatLogin'),
  syncWeChatContacts: () => call('gui:syncWeChatContacts'),
  listWeChatContacts: () => call('gui:listWeChatContacts'),
  getWeChatMessages: (contactId) => call('gui:getWeChatMessages', contactId),
  upsertWeChatContact: (input) => call('gui:upsertWeChatContact', input),
  removeWeChatContact: (id) => call('gui:removeWeChatContact', id),
  sendWeChatMessage: (payload) => call('gui:sendWeChatMessage', payload),
  getFeishuConfig: () => call('gui:getFeishuConfig'),
  saveFeishuConfig: (config) => call('gui:saveFeishuConfig', config),
  startFeishuService: () => call('gui:startFeishuService'),
  stopFeishuService: () => call('gui:stopFeishuService'),
  getQQConfig: () => call('gui:getQQConfig'),
  saveQQConfig: (config) => call('gui:saveQQConfig', config),
  startQQService: () => call('gui:startQQService'),
  stopQQService: () => call('gui:stopQQService'),
  listChannelContacts: (channel) => call('gui:listChannelContacts', channel),
  getChannelMessages: (contactId, channel) => call('gui:getChannelMessages', { contactId, channel }),
  upsertChannelContact: (input) => call('gui:upsertChannelContact', input),
  removeChannelContact: (id, channel) => call('gui:removeChannelContact', { id, channel }),
  sendChannelMessage: (payload) => call('gui:sendChannelMessage', payload),
  listBots: () => call('gui:listBots'),
  upsertBot: (bot) => call('gui:upsertBot', bot),
  deleteBot: (id) => call('gui:deleteBot', id),
  toggleBotStatus: (id, enabled) => call('gui:toggleBotStatus', { id, enabled }),
  testBotConnection: (bot) => call('gui:testBotConnection', bot),
  listServers: () => call('gui:listServers'),
  upsertServer: (input) => call('gui:upsertServer', input),
  removeServer: (id) => call('gui:removeServer', id),
  testServer: (id) => call('gui:testServer', id),
  testServerBotAlert: (payload) => call('gui:testServerBotAlert', payload),
  installServer: (id) => call('gui:installServer', id),
  onInstallProgress: (callback) => {
    ipcRenderer.on('gui:installProgress', (_event, data) => callback(data));
  },
  removeInstallProgressListeners: () => {
    ipcRenderer.removeAllListeners('gui:installProgress');
  },
  getServerInfo: (id) => call('gui:getServerInfo', id),
  getServerProcesses: (id, options) => call('gui:getServerProcesses', id, options),
  killServerProcess: (payload) => call('gui:killServerProcess', payload),
  execServerCommand: (payload) => call('gui:execServerCommand', payload),
  syncTarget: (input) => call('gui:syncTarget', input),
  chat: (input) => call('gui:chat', input),
  abortChat: () => call('gui:chat:abort'),
  onChatStream: (callback) => {
    ipcRenderer.on('gui:chat:stream', (_event, data) => callback(data));
  },
  removeChatStreamListeners: () => {
    ipcRenderer.removeAllListeners('gui:chat:stream');
  },
  listMcpTools: (refresh) => call('gui:mcp:listTools', { refresh }),
  callMcpTool: (payload) => call('gui:mcp:callTool', payload),
  logs: () => call('gui:logs'),
  clearLogs: () => call('gui:clearLogs'),
  toggleDevTools: () => call('gui:toggleDevTools'),
  openExternal: (url) => call('gui:openExternal', url),
});
