const { contextBridge, ipcRenderer } = require('electron');

async function call(channel, ...payload) {
  const result = await ipcRenderer.invoke(channel, ...payload);
  if (!result.ok) throw new Error(result.error);
  return result.data;
}

contextBridge.exposeInMainWorld('hap', {
  getUpdateState: () => call('gui:update:getState'),
  checkForUpdates: () => call('gui:update:check'),
  downloadUpdate: () => call('gui:update:download'),
  installUpdate: () => call('gui:update:install'),
  onUpdateState: (callback) => {
    const listener = (_event, state) => callback(state);
    ipcRenderer.on('gui:update:state', listener);
    return () => ipcRenderer.removeListener('gui:update:state', listener);
  },
  snapshot: () => call('gui:snapshot'),
  importProject: () => call('gui:importProject'),
  addProject: (input) => call('gui:addProject', input),
  removeProject: (id) => call('gui:removeProject', id),
  batchRemoveProjects: (ids) => call('gui:batchRemoveProjects', ids),
  upsertProvider: (input) => call('gui:upsertProvider', input),
  removeProvider: (id) => call('gui:removeProvider', id),
  batchRemoveProviders: (ids) => call('gui:batchRemoveProviders', ids),
  clearDefaultProviders: () => call('gui:clearDefaultProviders'),
  restoreDefaultProviders: () => call('gui:restoreDefaultProviders'),
  upsertModel: (input) => call('gui:upsertModel', input),
  removeModel: (alias) => call('gui:removeModel', alias),
  batchRemoveModels: (aliases) => call('gui:batchRemoveModels', aliases),
  setDefaultModel: (alias) => call('gui:setDefaultModel', alias),
  testModel: (alias) => call('gui:testModel', alias),
  upsertAgent: (input) => call('gui:upsertAgent', input),
  setDefaultAgent: (id) => call('gui:setDefaultAgent', id),
  removeAgent: (id) => call('gui:removeAgent', id),
  openInVsCode: (path) => call('gui:openInVsCode', path),
  openInExplorer: (path) => call('gui:openInExplorer', path),
  openInTerminal: (path) => call('gui:openInTerminal', path),
  testProvider: (idOrConfig) => call('gui:testProvider', idOrConfig),
  fetchProviderModels: (providerId, options) => call('gui:fetchProviderModels', { providerId, options }),
  getProviderApiKey: (providerId) => call('gui:getProviderApiKey', providerId),
  getEnvVars: () => call('gui:getEnvVars'),
  saveEnvVar: (input) => call('gui:saveEnvVar', input),
  deleteEnvVar: (key) => call('gui:deleteEnvVar', key),
  batchSaveEnvVars: (entries) => call('gui:batchSaveEnvVars', entries),
  generateImage: (payload) => call('gui:generateImage', payload),
  listSkills: () => call('gui:listSkills'),
  installSkill: (repoUrl) => call('gui:installSkill', repoUrl),
  importSkill: (skillData) => call('gui:importSkill', skillData),
  toggleSkill: (id, enabled) => call('gui:toggleSkill', { id, enabled }),
  uninstallSkill: (id) => call('gui:uninstallSkill', id),
  listPlugins: () => call('gui:listPlugins'),
  togglePlugin: (id, enabled) => call('gui:togglePlugin', { id, enabled }),
  upsertPlugin: (plugin) => call('gui:upsertPlugin', plugin),
  getPermissions: () => call('gui:getPermissions'),
  updatePermissions: (config) => call('gui:updatePermissions', config),
  getGitStatus: (projectPath) => call('gui:getGitStatus', projectPath),
  gitCommit: (projectPath, message) => call('gui:gitCommit', { projectPath, message }),
  gitStashCommit: (projectPath, message) => call('gui:gitStashCommit', { projectPath, message }),
  gitGetCommitHistory: (projectPath, limit) => call('gui:gitGetCommitHistory', { projectPath, limit }),
  gitRollbackCommit: (projectPath, commitHash, mode) => call('gui:gitRollbackCommit', { projectPath, commitHash, mode }),
  gitRevertCommit: (projectPath, commitHash) => call('gui:gitRevertCommit', { projectPath, commitHash }),
  gitShowCommit: (projectPath, commitHash) => call('gui:gitShowCommit', { projectPath, commitHash }),
  gitPush: (projectPath) => call('gui:gitPush', projectPath),
  gitPull: (projectPath) => call('gui:gitPull', projectPath),
  getGitAuthInfo: (projectPath) => call('gui:getGitAuthInfo', projectPath),
  configureGitSsh: (projectPath) => call('gui:configureGitSsh', projectPath),
  configureGitToken: (projectPath, username, token) => call('gui:configureGitToken', { projectPath, username, token }),
  gitListBranches: (projectPath) => call('gui:gitListBranches', projectPath),
  gitCheckoutBranch: (projectPath, branchName, createNew) => call('gui:gitCheckoutBranch', { projectPath, branchName, createNew }),
  gitMergeBranch: (projectPath, targetBranch, options) => call('gui:gitMergeBranch', { projectPath, targetBranch, options }),
  gitMergeAbort: (projectPath) => call('gui:gitMergeAbort', projectPath),
  gitRebaseBranch: (projectPath, targetBranch) => call('gui:gitRebaseBranch', { projectPath, targetBranch }),
  gitRebaseAbort: (projectPath) => call('gui:gitRebaseAbort', projectPath),
  gitRebaseContinue: (projectPath) => call('gui:gitRebaseContinue', projectPath),
  gitDiff: (projectPath, file, isStaged) => call('gui:gitDiff', { projectPath, file, isStaged }),
  getVisualDiff: (projectPath, file, isStaged) => call('gui:getVisualDiff', { projectPath, file, isStaged }),
  revertFileDiff: (projectPath, file) => call('gui:revertFileDiff', { projectPath, file }),
  revertAllFiles: (projectPath) => call('gui:revertAllFiles', projectPath),
  stageFileDiff: (projectPath, file) => call('gui:stageFileDiff', { projectPath, file }),
  unstageFileDiff: (projectPath, file) => call('gui:unstageFileDiff', { projectPath, file }),
  stageAllFiles: (projectPath) => call('gui:stageAllFiles', projectPath),
  unstageAllFiles: (projectPath) => call('gui:unstageAllFiles', projectPath),
  stageHunk: (projectPath, file, patch) => call('gui:stageHunk', { projectPath, file, patch }),
  revertHunk: (projectPath, file, patch) => call('gui:revertHunk', { projectPath, file, patch }),
  getProjectCommitRule: (projectPath) => call('gui:getProjectCommitRule', projectPath),
  saveProjectCommitRule: (projectPath, content, fileName) => call('gui:saveProjectCommitRule', { projectPath, content, fileName }),
  listSchedules: () => call('gui:listSchedules'),
  upsertSchedule: (input) => call('gui:upsertSchedule', input),
  removeSchedule: (id) => call('gui:removeSchedule', id),
  toggleSchedule: (id, enabled) => call('gui:toggleSchedule', { id, enabled }),
  runScheduleNow: (id) => call('gui:runScheduleNow', id),
  getScheduleHistory: (scheduleId) => call('gui:getScheduleHistory', scheduleId),
  listMemories: (category) => call('gui:listMemories', category),
  addMemory: (input) => call('gui:addMemory', input),
  searchMemories: (query, limit) => call('gui:searchMemories', { query, limit }),
  removeMemory: (id) => call('gui:removeMemory', id),
  updateMemory: (id, patch) => call('gui:updateMemory', { id, patch }),
  rebuildMemoryEmbeddings: () => call('gui:rebuildMemoryEmbeddings'),
  findDefinition: (symbol, workspace) => call('gui:findDefinition', { symbol, workspace }),
  findReferences: (symbol, workspace) => call('gui:findReferences', { symbol, workspace }),
  listSymbols: (file) => call('gui:listSymbols', file),
  getWebInfo: () => call('gui:getWebInfo'),
  getHostSysInfo: () => call('gui:getHostSysInfo'),
  scanDiskCleanable: (server) => call('gui:scanDiskCleanable', server),
  executeDiskCleanup: (payload) => call('gui:executeDiskCleanup', payload),
  getIpGeoInfo: (ip) => call('gui:getIpGeoInfo', ip),
  getTelegramConfig: () => call('gui:getTelegramConfig'),
  saveTelegramConfig: (config) => call('gui:saveTelegramConfig', config),
  testTelegramBot: (token) => call('gui:testTelegramBot', token),
  startTelegramService: () => call('gui:startTelegramService'),
  stopTelegramService: () => call('gui:stopTelegramService'),
  getWeChatConfig: () => call('gui:getWeChatConfig'),
  saveWeChatConfig: (config) => call('gui:saveWeChatConfig', config),
  startWeChatService: () => call('gui:startWeChatService'),
  logoutWeChat: () => call('gui:logoutWeChat'),
  stopWeChatService: () => call('gui:stopWeChatService'),
  refreshWeChatQr: () => call('gui:refreshWeChatQr'),
  confirmWeChatLogin: () => call('gui:confirmWeChatLogin'),
  syncWeChatContacts: () => call('gui:syncWeChatContacts'),
  listWeChatContacts: () => call('gui:listWeChatContacts'),
  getWeChatMessages: (contactId) => call('gui:getWeChatMessages', contactId),
  upsertWeChatContact: (input) => call('gui:upsertWeChatContact', input),
  removeWeChatContact: (id) => call('gui:removeWeChatContact', id),
  sendWeChatMessage: (payload) => call('gui:sendWeChatMessage', payload),
  getFeishuConfig: () => call('gui:getFeishuConfig'),
  saveFeishuConfig: (config) => call('gui:saveFeishuConfig', config),
  startFeishuService: () => call('gui:startFeishuService'),
  stopFeishuService: () => call('gui:stopFeishuService'),
  getQQConfig: () => call('gui:getQQConfig'),
  saveQQConfig: (config) => call('gui:saveQQConfig', config),
  startQQService: () => call('gui:startQQService'),
  stopQQService: () => call('gui:stopQQService'),
  listChannelContacts: (channel) => call('gui:listChannelContacts', channel),
  getChannelMessages: (contactId, channel) => call('gui:getChannelMessages', { contactId, channel }),
  upsertChannelContact: (input) => call('gui:upsertChannelContact', input),
  removeChannelContact: (id, channel) => call('gui:removeChannelContact', { id, channel }),
  sendChannelMessage: (payload) => call('gui:sendChannelMessage', payload),
  listBots: () => call('gui:listBots'),
  upsertBot: (bot) => call('gui:upsertBot', bot),
  deleteBot: (id) => call('gui:deleteBot', id),
  toggleBotStatus: (id, enabled) => call('gui:toggleBotStatus', { id, enabled }),
  testBotConnection: (bot) => call('gui:testBotConnection', bot),
  listServers: () => call('gui:listServers'),
  upsertServer: (input) => call('gui:upsertServer', input),
  removeServer: (id) => call('gui:removeServer', id),
  testServer: (id) => call('gui:testServer', id),
  testServerBotAlert: (payload) => call('gui:testServerBotAlert', payload),
  installServer: (id) => call('gui:installServer', id),
  onInstallProgress: (callback) => {
    ipcRenderer.on('gui:installProgress', (_event, data) => callback(data));
  },
  removeInstallProgressListeners: () => {
    ipcRenderer.removeAllListeners('gui:installProgress');
  },
  getServerInfo: (id) => call('gui:getServerInfo', id),
  getServerProcesses: (id, options) => call('gui:getServerProcesses', id, options),
  killServerProcess: (payload) => call('gui:killServerProcess', payload),
  execServerCommand: (payload) => call('gui:execServerCommand', payload),
  syncTarget: (input) => call('gui:syncTarget', input),
  chat: (input) => call('gui:chat', input),
  abortChat: () => call('gui:chat:abort'),
  onChatStream: (callback) => {
    ipcRenderer.on('gui:chat:stream', (_event, data) => callback(data));
  },
  removeChatStreamListeners: () => {
    ipcRenderer.removeAllListeners('gui:chat:stream');
  },
  listMcpTools: (refresh) => call('gui:mcp:listTools', { refresh }),
  callMcpTool: (payload) => call('gui:mcp:callTool', payload),
  getOllamaStatus: () => call('gui:ollama:getStatus'),
  getRecommendedModels: (categoryFilter) => call('gui:ollama:getRecommendedModels', categoryFilter),
  startOllamaService: () => call('gui:ollama:startService'),
  pullOllamaModel: (modelTag) => call('gui:ollama:pullModel', modelTag),
  cancelOllamaPull: (modelTag) => call('gui:ollama:cancelPull', modelTag),
  deleteOllamaModel: (modelTag) => call('gui:ollama:deleteModel', modelTag),
  onOllamaPullProgress: (callback) => {
    const listener = (_event, data) => callback(data);
    ipcRenderer.on('gui:ollama:pullProgress', listener);
    return () => ipcRenderer.removeListener('gui:ollama:pullProgress', listener);
  },
  logs: () => call('gui:logs'),
  clearLogs: () => call('gui:clearLogs'),
  toggleDevTools: () => call('gui:toggleDevTools'),
  openExternal: (url) => call('gui:openExternal', url),
  minimizeWindow: () => call('gui:window:minimize'),
  maximizeWindow: () => call('gui:window:maximize'),
  closeWindow: () => call('gui:window:close'),
  setWindowOpacity: (opacity) => call('gui:window:setOpacity', opacity),
  getWindowOpacity: () => call('gui:window:getOpacity'),
  setAlwaysOnTop: (flag) => call('gui:window:setAlwaysOnTop', flag),
  setMiniMode: (enable) => call('gui:window:setMiniMode', enable),
  getMiniMode: () => call('gui:window:getMiniMode'),
  onMiniModeChanged: (callback) => {
    ipcRenderer.on('gui:window:miniModeChanged', (_event, data) => callback(data));
  },
  removeMiniModeListeners: () => {
    ipcRenderer.removeAllListeners('gui:window:miniModeChanged');
  },
  getGatewayOverview: () => call('gui:getGatewayOverview'),
  getGatewayConfig: () => call('gui:getGatewayConfig'),
  updateGatewayConfig: (patch) => call('gui:updateGatewayConfig', patch),
  listGatewayKeys: () => call('gui:listGatewayKeys'),
  createGatewayKey: (input) => call('gui:createGatewayKey', input),
  updateGatewayKey: (id, patch) => call('gui:updateGatewayKey', { id, patch }),
  deleteGatewayKey: (id) => call('gui:deleteGatewayKey', id),
  listGatewayAliases: () => call('gui:listGatewayAliases'),
  upsertGatewayAlias: (input) => call('gui:upsertGatewayAlias', input),
  deleteGatewayAlias: (id) => call('gui:deleteGatewayAlias', id),
  listGatewayLogs: (limit) => call('gui:listGatewayLogs', limit),
  clearGatewayLogs: () => call('gui:clearGatewayLogs'),
  getGatewayClientPresets: (key) => call('gui:getGatewayClientPresets', key),
});
