/**
 * Standalone Remote Daemon Script Generator
 * 
 * Generates a self-contained, zero-dependency Node.js daemon script
 * that runs on the remote server. Uses only Node.js standard library (http, crypto, os, child_process, fs).
 */

export function generateRemoteDaemonScript(options: { port: number; token: string }): string {
  return `#!/usr/bin/env node
// HAP Remote Agent Daemon (Self-contained, Zero-dependency)
// Auto-generated by Hermes Agent Platform

import http from 'node:http';
import os from 'node:os';
import fs from 'node:fs';
import { spawn } from 'node:child_process';
import crypto from 'node:crypto';

const PORT = ${options.port};
const AUTH_TOKEN = ${JSON.stringify(options.token)};
const START_TIME = Date.now();

function getCpuUsage() {
  const cpus = os.cpus();
  let totalUser = 0;
  let totalSys = 0;
  let totalIdle = 0;
  for (const cpu of cpus) {
    totalUser += cpu.times.user;
    totalSys += cpu.times.sys;
    totalIdle += cpu.times.idle;
  }
  const total = totalUser + totalSys + totalIdle;
  return {
    count: cpus.length,
    model: cpus[0]?.model || 'Unknown CPU',
    usagePercent: total > 0 ? Number((((totalUser + totalSys) / total) * 100).toFixed(1)) : 0,
  };
}

function getSystemInfo() {
  const cpu = getCpuUsage();
  const totalMem = os.totalmem();
  const freeMem = os.freemem();
  const usedMemPercent = totalMem > 0 ? Number((((totalMem - freeMem) / totalMem) * 100).toFixed(1)) : 0;
  
  let osRelease = os.release();
  try {
    if (fs.existsSync('/etc/os-release')) {
      const osFile = fs.readFileSync('/etc/os-release', 'utf-8');
      const prettyMatch = osFile.match(/PRETTY_NAME="?([^"\\n]+)"?/);
      if (prettyMatch) osRelease = prettyMatch[1];
    }
  } catch {}

  return {
    hostname: os.hostname(),
    platform: os.platform(),
    arch: os.arch(),
    osRelease,
    uptimeSeconds: Math.floor(os.uptime()),
    cpuCount: cpu.count,
    cpuModel: cpu.model,
    cpuUsagePercent: cpu.usagePercent,
    totalMemBytes: totalMem,
    freeMemBytes: freeMem,
    usedMemPercent,
    loadAvg: os.loadavg().map(n => Number(n.toFixed(2))),
    nodeVersion: process.version,
    timestamp: Date.now(),
  };
}

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-HAP-Token');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Health check endpoint (can be checked without token for ping)
  if (req.url === '/health' || req.url === '/ping') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, status: 'online', uptime: Date.now() - START_TIME }));
    return;
  }

  // Authenticate
  const authHeader = req.headers['authorization'] || req.headers['x-hap-token'];
  const token = typeof authHeader === 'string' && authHeader.startsWith('Bearer ')
    ? authHeader.slice(7).trim()
    : authHeader;

  if (AUTH_TOKEN && token !== AUTH_TOKEN) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: false, error: 'Unauthorized: Invalid token' }));
    return;
  }

  if (req.url === '/api/sysinfo' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, data: getSystemInfo() }));
    return;
  }

  if (req.url === '/api/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try {
        const payload = JSON.parse(body || '{}');
        const command = payload.command;
        const cwd = payload.cwd || process.env.HOME || '/root';
        const stream = payload.stream === true;

        if (!command || typeof command !== 'string') {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: false, error: 'Missing command' }));
          return;
        }

        const startTime = Date.now();
        const child = spawn('/bin/sh', ['-c', command], {
          cwd,
          env: { ...process.env, TERM: 'xterm-256color' },
        });

        if (stream) {
          res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
          });

          child.stdout.on('data', chunk => {
            res.write(\`data: \${JSON.stringify({ type: 'stdout', text: chunk.toString('utf-8') })}\\n\\n\`);
          });

          child.stderr.on('data', chunk => {
            res.write(\`data: \${JSON.stringify({ type: 'stderr', text: chunk.toString('utf-8') })}\\n\\n\`);
          });

          child.on('close', code => {
            res.write(\`data: \${JSON.stringify({ type: 'exit', code, durationMs: Date.now() - startTime })}\\n\\n\`);
            res.end();
          });

          child.on('error', err => {
            res.write(\`data: \${JSON.stringify({ type: 'error', error: err.message })}\\n\\n\`);
            res.end();
          });
        } else {
          let stdout = '';
          let stderr = '';

          child.stdout.on('data', chunk => { stdout += chunk.toString('utf-8'); });
          child.stderr.on('data', chunk => { stderr += chunk.toString('utf-8'); });

          child.on('close', code => {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({
              ok: code === 0,
              data: {
                code,
                stdout,
                stderr,
                durationMs: Date.now() - startTime,
              }
            }));
          });

          child.on('error', err => {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ ok: false, error: err.message }));
          });
        }
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: 'Invalid JSON payload' }));
      }
    });
    return;
  }

  // Fallback 404
  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ ok: false, error: 'Endpoint not found' }));
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(\`[HAP-Daemon] Server running on 0.0.0.0:\${PORT}\`);
});
`;
}
