/**
 * Standalone Remote Daemon Script Generator
 * 
 * Generates a self-contained, zero-dependency Node.js daemon script
 * that runs on the remote server. Uses only Node.js standard library (http, crypto, os, child_process, fs).
 */

export function generateRemoteDaemonScript(options: { port: number; token: string; bind?: string | undefined }): string {
  return `#!/usr/bin/env node
// HAP Remote Agent Daemon (Self-contained, Zero-dependency)
// Auto-generated by Hermes Agent Platform

import http from 'node:http';
import os from 'node:os';
import fs from 'node:fs';
import { spawn, execFileSync } from 'node:child_process';
import crypto from 'node:crypto';

const PORT = ${options.port};
const BIND_HOST = ${JSON.stringify(options.bind ?? '127.0.0.1')};
const AUTH_TOKEN = ${JSON.stringify(options.token)};
const START_TIME = Date.now();
const PROTECTED_PIDS = new Set([process.pid, 1]);
const MAX_BODY_BYTES = 1 * 1024 * 1024;
const MAX_OUTPUT_BYTES = 1 * 1024 * 1024;
const MAX_CONCURRENT_EXEC = 4;
let activeExec = 0;

function getCpuUsage() {
  const cpus = os.cpus();
  let totalUser = 0;
  let totalSys = 0;
  let totalIdle = 0;
  for (const cpu of cpus) {
    totalUser += cpu.times.user;
    totalSys += cpu.times.sys;
    totalIdle += cpu.times.idle;
  }
  const total = totalUser + totalSys + totalIdle;
  return {
    count: cpus.length,
    model: cpus[0]?.model || 'Unknown CPU',
    usagePercent: total > 0 ? Number((((totalUser + totalSys) / total) * 100).toFixed(1)) : 0,
  };
}

function getSystemInfo() {
  const cpu = getCpuUsage();
  const totalMem = os.totalmem();
  const freeMem = os.freemem();
  const usedMemPercent = totalMem > 0 ? Number((((totalMem - freeMem) / totalMem) * 100).toFixed(1)) : 0;
  
  let osRelease = os.release();
  try {
    if (fs.existsSync('/etc/os-release')) {
      const osFile = fs.readFileSync('/etc/os-release', 'utf-8');
      const prettyMatch = osFile.match(/PRETTY_NAME="?([^"\\n]+)"?/);
      if (prettyMatch) osRelease = prettyMatch[1];
    }
  } catch {}

  return {
    hostname: os.hostname(),
    platform: os.platform(),
    arch: os.arch(),
    osRelease,
    uptimeSeconds: Math.floor(os.uptime()),
    cpuCount: cpu.count,
    cpuModel: cpu.model,
    cpuUsagePercent: cpu.usagePercent,
    totalMemBytes: totalMem,
    freeMemBytes: freeMem,
    usedMemPercent,
    loadAvg: os.loadavg().map(n => Number(n.toFixed(2))),
    nodeVersion: process.version,
    ...getDiskInfo(),
    timestamp: Date.now(),
  };
}

function getDiskInfo() {
  try {
    const line = execFileSync('df', ['-kP', '/'], { encoding: 'utf8' }).trim().split(/\\r?\\n/).pop() || '';
    const m = line.match(/^\\S+\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)%\\s+(.+)$/);
    if (m) {
      const total = Number(m[1]) * 1024;
      const used = Number(m[2]) * 1024;
      const free = Number(m[3]) * 1024;
      return { diskTotalBytes: total, diskFreeBytes: free, diskUsedBytes: used, diskUsedPercent: Number(m[4]), diskMount: m[5] };
    }
  } catch {}
  return { diskTotalBytes: 0, diskFreeBytes: 0, diskUsedBytes: 0, diskUsedPercent: 0 };
}

function normalizeProcessLimit(value) {
  if (value === undefined || value === null) return 100;
  const n = Number(value);
  return Number.isSafeInteger(n) && n >= 1 && n <= 500 ? n : null;
}

function parseProcessLine(line) {
  const trimmed = line.trim();
  const elapsedFromStart = (startTime) => {
    const parsed = Date.parse(startTime);
    return Number.isFinite(parsed) ? Math.max(0, Math.floor((Date.now() - parsed) / 1000)) : undefined;
  };
  let match = trimmed.match(/^(\\d+)\\s+(\\d+)\\s+(\\S+)\\s+([\\d.]+)\\s+([\\d.]+)\\s+(\\d+)\\s+((?:Sun|Mon|Tue|Wed|Thu|Fri|Sat)\\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\\s+\\d{1,2}\\s+\\d{2}:\\d{2}:\\d{2}\\s+\\d{4})\\s+(.*)$/);
  if (match) {
    const process = {
      pid: Number(match[1]),
      ppid: Number(match[2]),
      user: match[3],
      cpuPercent: Number(match[4]),
      memPercent: Number(match[5]),
      elapsedSeconds: Number(match[6]),
      startTime: match[7].replace(/\\s+/g, ' ').trim(),
      command: match[8] || '',
    };
    return Number.isSafeInteger(process.pid) && process.pid > 0
      && Number.isSafeInteger(process.ppid) && process.ppid >= 0
      && Number.isFinite(process.cpuPercent) && Number.isFinite(process.memPercent)
      ? process
      : null;
  }

  match = trimmed.match(/^(\\d+)\\s+(\\d+)\\s+(\\S+)\\s+([\\d.]+)\\s+([\\d.]+)\\s+((?:Sun|Mon|Tue|Wed|Thu|Fri|Sat)\\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\\s+\\d{1,2}\\s+\\d{2}:\\d{2}:\\d{2}\\s+\\d{4})\\s+(.*)$/);
  if (match) {
    const process = {
      pid: Number(match[1]),
      ppid: Number(match[2]),
      user: match[3],
      cpuPercent: Number(match[4]),
      memPercent: Number(match[5]),
      startTime: match[6].replace(/\\s+/g, ' ').trim(),
      command: match[7] || '',
    };
    const elapsedSeconds = elapsedFromStart(process.startTime);
    if (elapsedSeconds !== undefined) process.elapsedSeconds = elapsedSeconds;
    return Number.isSafeInteger(process.pid) && process.pid > 0
      && Number.isSafeInteger(process.ppid) && process.ppid >= 0
      && Number.isFinite(process.cpuPercent) && Number.isFinite(process.memPercent)
      ? process
      : null;
  }

  match = trimmed.match(/^(\\d+)\\s+(\\d+)\\s+(\\S+)\\s+([\\d.]+)\\s+([\\d.]+)\\s+(\\d+)\\s+(.*)$/);
  if (!match) return null;
  const process = {
    pid: Number(match[1]),
    ppid: Number(match[2]),
    user: match[3],
    cpuPercent: Number(match[4]),
    memPercent: Number(match[5]),
    elapsedSeconds: Number(match[6]),
    command: match[7] || '',
  };
  return Number.isSafeInteger(process.pid) && process.pid > 0
    && Number.isSafeInteger(process.ppid) && process.ppid >= 0
    && Number.isFinite(process.cpuPercent) && Number.isFinite(process.memPercent)
    ? process
    : null;
}

function readProcessRows() {
  const formats = [
    'pid=,ppid=,user=,%cpu=,%mem=,etimes=,lstart=,args=',
    'pid=,ppid=,user=,%cpu=,%mem=,lstart=,args=',
    'pid=,ppid=,user=,%cpu=,%mem=,etimes=,args=',
  ];
  for (const format of formats) {
    try {
      const text = execFileSync('ps', ['-eo', format], {
        encoding: 'utf8',
        maxBuffer: 4 * 1024 * 1024,
        env: { ...process.env, LC_ALL: 'C' },
      });
      return text.split(/\\r?\\n/).filter(Boolean).map(parseProcessLine).filter(Boolean);
    } catch {}
  }
  return [];
}

function listProcesses(limit) {
  const n = normalizeProcessLimit(limit);
  if (n === null) return null;
  try {
    return { processes: readProcessRows().slice(0, n), limit: n, timestamp: Date.now() };
  } catch {
    return { processes: [], limit: n, timestamp: Date.now() };
  }
}

function rejectRequest(res, status, error) {
  if (res.headersSent) return;
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ ok: false, error }));
}

function readBody(req, res, callback, onReject = () => {}) {
  const declared = Number(req.headers['content-length'] || 0);
  if (Number.isFinite(declared) && declared > MAX_BODY_BYTES) {
    onReject();
    rejectRequest(res, 413, 'Request body too large');
    req.resume();
    return;
  }
  let body = '';
  let size = 0;
  let done = false;
  const abort = () => {
    if (done) return;
    done = true;
    onReject();
    req.destroy();
  };
  req.on('aborted', abort);
  req.on('close', () => {
    if (!req.complete) abort();
  });
  req.on('data', chunk => {
    if (done) return;
    size += chunk.length;
    if (size > MAX_BODY_BYTES) {
      done = true;
      onReject();
      rejectRequest(res, 413, 'Request body too large');
      req.destroy();
      return;
    }
    body += chunk.toString('utf8');
  });
  req.on('end', () => {
    if (done) return;
    done = true;
    req.removeListener('aborted', abort);
    callback(body);
  });
}

process.on('uncaughtException', (err) => {
  console.error('[HAP-Daemon] Uncaught Exception:', err);
});

process.on('unhandledRejection', (reason) => {
  console.error('[HAP-Daemon] Unhandled Rejection:', reason);
});

const server = http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-HAP-Token');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Health check endpoint (can be checked without token for ping)
  if (req.url === '/health' || req.url === '/ping' || req.url === '/') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, status: 'online', uptime: Date.now() - START_TIME }));
    return;
  }

  // Authenticate
  const authHeader = req.headers['authorization'] || req.headers['x-hap-token'];
  const token = typeof authHeader === 'string' && authHeader.startsWith('Bearer ')
    ? authHeader.slice(7).trim()
    : authHeader;

  if (AUTH_TOKEN && token !== AUTH_TOKEN) {
    res.writeHead(401, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: false, error: 'Unauthorized: Invalid token' }));
    return;
  }

  if (req.url === '/api/sysinfo' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, data: getSystemInfo() }));
    return;
  }

  const requestUrl = new URL(req.url || '/', 'http://localhost');

  if (req.method === 'GET' && requestUrl.pathname === '/api/processes') {
    const query = requestUrl.searchParams;
    const requestedPid = query.get('pid');
    if (requestedPid !== null) {
      const pidNum = Number(requestedPid);
      if (!Number.isSafeInteger(pidNum) || pidNum <= 0) {
        rejectRequest(res, 400, 'Invalid PID');
        return;
      }
      const all = readProcessRows();
      const match = all.find(p => p && p.pid === pidNum);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ ok: true, data: { processes: match ? [match] : [], limit: 1, timestamp: Date.now() } }));
      return;
    }
    const requestedLimit = query.get('limit');
    const limit = normalizeProcessLimit(requestedLimit === null ? undefined : requestedLimit);
    if (limit === null) {
      rejectRequest(res, 400, 'limit 必须是 1-500 的整数');
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, data: listProcesses(limit) }));
    return;
  }

  if (req.method === 'POST' && requestUrl.pathname.match(/^\\/api\\/processes\\/[^/]+\\/kill$/)) {
    const pidText = requestUrl.pathname.split('/')[3] || '';
    if (!/^\\d+$/.test(pidText)) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ ok: false, error: 'Invalid PID' }));
      return;
    }
    const pid = Number(pidText);
    if (!Number.isSafeInteger(pid) || pid <= 0) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ ok: false, error: 'Invalid PID' }));
      return;
    }
    readBody(req, res, (body) => {
      let payload;
      try {
        payload = JSON.parse(body || '{}');
      } catch {
        rejectRequest(res, 400, 'Invalid JSON payload');
        return;
      }
      if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) {
        rejectRequest(res, 400, 'Invalid JSON payload');
        return;
      }
      const signal = payload.signal;
      if (signal !== 'TERM' && signal !== 'KILL') {
        rejectRequest(res, 400, 'Invalid signal');
        return;
      }
      if (PROTECTED_PIDS.has(pid)) {
        rejectRequest(res, 403, 'Protected PID');
        return;
      }
      const hasExpectedStartTime = Object.prototype.hasOwnProperty.call(payload, 'expectedStartTime');
      if (hasExpectedStartTime && (typeof payload.expectedStartTime !== 'string' || !payload.expectedStartTime.trim())) {
        rejectRequest(res, 400, 'Invalid expected start time');
        return;
      }
      if (hasExpectedStartTime) {
        const current = readProcessRows().find(p => p && p.pid === pid);
        if (!current || current.startTime !== payload.expectedStartTime) {
          rejectRequest(res, 409, 'Process start time mismatch');
          return;
        }
      }
      try {
        process.kill(pid, signal === 'KILL' ? 'SIGKILL' : 'SIGTERM');
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, data: { pid, signal, killed: true } }));
      } catch (err) {
        rejectRequest(res, 404, err.message);
      }
    });
    return;
  }

  if (req.url === '/api/exec' && req.method === 'POST') {
    if (activeExec >= MAX_CONCURRENT_EXEC) {
      rejectRequest(res, 429, 'Too many concurrent executions');
      req.resume();
      return;
    }
    activeExec += 1;
    let released = false;
    const release = () => {
      if (released) return;
      released = true;
      activeExec = Math.max(0, activeExec - 1);
    };
    readBody(req, res, (body) => {
      try {
        const payload = JSON.parse(body || '{}');
        const command = payload.command;
        const cwd = payload.cwd || process.env.HOME || '/root';
        const stream = payload.stream === true;

        if (!command || typeof command !== 'string') {
          release();
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ ok: false, error: 'Missing command' }));
          return;
        }

        const startTime = Date.now();
        const child = spawn('/bin/sh', ['-c', command], {
          cwd,
          env: { ...process.env, TERM: 'xterm-256color' },
        });
        let clientGone = false;
        const terminateChild = () => {
          if (res.writableFinished) return;
          clientGone = true;
          if (!child.killed) child.kill('SIGTERM');
          setTimeout(() => { if (!child.killed) child.kill('SIGKILL'); }, 1000).unref();
        };
        req.on('aborted', terminateChild);
        res.on('close', terminateChild);
        child.on('close', () => {
          req.removeListener('aborted', terminateChild);
          res.removeListener('close', terminateChild);
          release();
        });

        if (stream) {
          res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
          });

          let streamBytes = 0;
          child.stdout.on('data', chunk => {
            if (clientGone) return;
            const remaining = MAX_OUTPUT_BYTES - streamBytes;
            if (remaining <= 0) return;
            const text = chunk.toString('utf-8').slice(0, remaining);
            streamBytes += Buffer.byteLength(text);
            res.write(\`data: \${JSON.stringify({ type: 'stdout', text })}\\n\\n\`);
            if (streamBytes >= MAX_OUTPUT_BYTES) terminateChild();
          });

          child.stderr.on('data', chunk => {
            if (clientGone) return;
            const remaining = MAX_OUTPUT_BYTES - streamBytes;
            if (remaining <= 0) return;
            const text = chunk.toString('utf-8').slice(0, remaining);
            streamBytes += Buffer.byteLength(text);
            res.write(\`data: \${JSON.stringify({ type: 'stderr', text })}\\n\\n\`);
            if (streamBytes >= MAX_OUTPUT_BYTES) terminateChild();
          });

          child.on('close', code => {
            if (!res.writableEnded) {
              res.write(\`data: \${JSON.stringify({ type: 'exit', code, durationMs: Date.now() - startTime })}\\n\\n\`);
              res.end();
            }
          });

          child.on('error', err => {
            if (!res.writableEnded) {
              res.write(\`data: \${JSON.stringify({ type: 'error', error: err.message })}\\n\\n\`);
              res.end();
            }
          });
        } else {
          let stdout = '';
          let stderr = '';

          let outputBytes = 0;
          const appendOutput = (target, chunk) => {
            const remaining = MAX_OUTPUT_BYTES - outputBytes;
            if (remaining <= 0) return target;
            const text = chunk.toString('utf-8').slice(0, remaining);
            outputBytes += Buffer.byteLength(text);
            return target + text;
          };
          child.stdout.on('data', chunk => {
            stdout = appendOutput(stdout, chunk);
            if (outputBytes >= MAX_OUTPUT_BYTES) terminateChild();
          });
          child.stderr.on('data', chunk => {
            stderr = appendOutput(stderr, chunk);
            if (outputBytes >= MAX_OUTPUT_BYTES) terminateChild();
          });

          child.on('close', code => {
            if (res.writableEnded) return;
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({
              ok: code === 0,
              data: {
                code,
                stdout,
                stderr,
                durationMs: Date.now() - startTime,
              }
            }));
          });

          child.on('error', err => {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ ok: false, error: err.message }));
          });
        }
      } catch (err) {
        release();
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: 'Invalid JSON payload' }));
      }
    }, release);
    return;
  }

  // Fallback 404
  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ ok: false, error: 'Endpoint not found' }));
});

server.on('error', (err) => {
  console.error(\`[HAP-Daemon] Server error: \${err.message}\`);
  process.exit(1);
});

server.listen(PORT, BIND_HOST, () => {
  console.log(\`[HAP-Daemon] Server running on \${BIND_HOST}:\${PORT}\`);
});
`;
}
